# Generated by Django 3.1.3 on 2020-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.PositiveBigIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
