# Generated by Django 3.1.3 on 2020-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
