# Generated by Django 3.1.3 on 2020-12-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='card_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
