# Generated by Django 3.1.3 on 2020-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201210_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='card_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
