# Generated by Django 3.1.3 on 2020-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rx',
            name='image',
            field=models.ImageField(default='', max_length=255, upload_to='public/rx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rx',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('H', 'On Hold'), ('P', 'Prepared'), ('R', 'Ready For Pick-up'), ('F', 'Finished')], default='A', max_length=1),
        ),
    ]
