# Generated by Django 3.1.3 on 2020-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0002_auto_20201203_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rx',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('H', 'On Hold'), ('P', 'Prepared'), ('R', 'Ready For Pick-up'), ('F', 'Finished')], default='A', max_length=1),
        ),
    ]
