# Generated by Django 3.1.3 on 2020-12-11 07:46

import django.core.validators
from django.db import migrations, models
import rx.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0004_rx_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rx',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AlterField(
            model_name='rx',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, validators=[rx.validators.contains_only_letters]),
        ),
        migrations.AlterField(
            model_name='rx',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, validators=[rx.validators.contains_only_letters]),
        ),
    ]
