# Generated by Django 3.1.3 on 2020-12-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0007_onhold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onhold',
            old_name='pet',
            new_name='rx',
        ),
    ]
