# Generated by Django 3.1.3 on 2020-12-12 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0008_auto_20201211_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='onhold',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
